import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { motion } from 'framer-motion'
import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import clsx from 'clsx'
import Router from 'next/router'
import NProgress from 'nprogress'

import GBIcon from '../assets/gb.svg'
import LTIcon from '../assets/lt.svg'
import NextImage from 'next/image'

import 'nprogress/nprogress.css'

// Global
import { MainLayout } from 'components/global'

Router.events.on('routeChangeStart', () => NProgress.start())
Router.events.on('routeChangeComplete', () => NProgress.done())
Router.events.on('routeChangeError', () => NProgress.done())

function MyApp({ Component, pageProps }: AppProps) {
  const { locale, locales, asPath: path, route } = useRouter()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <MainLayout>
        {/* <motion.div
        className="flex-1"
        key={route}
        initial="initial"
        animate="animate"
        transition={{
          duration: 0.5,
        }}
        variants={{
          initial: {
            x: -50,
            opacity: 0,
          },
          animate: {
            x: 0,
            opacity: 1,
          },
        }}
      > */}
        <Component {...pageProps} />
        {/* </motion.div> */}
      </MainLayout>
    </div>
  )
}

export default MyApp
