import "../styles/globals.css";
import type { AppProps } from "next/app";
import { motion } from "framer-motion";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

function MyApp({ Component, pageProps, router }: AppProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="p-4 flex justify-end border-b border-gray-200">
        <div className="flex gap-3">
          <Link href="/">
            <a className={styles.link}>Home</a>
          </Link>
          <Link href="/projects">
            <a className={styles.link}>Projects</a>
          </Link>
          <Link href="/about">
            <a className={styles.link}>About</a>
          </Link>
        </div>
      </header>
      <motion.div
        className="flex-1"
        key={router.route}
        initial="initial"
        animate="animate"
        transition={{
          duration: 0.5,
        }}
        variants={{
          initial: {
            x: -50,
            opacity: 0,
          },
          animate: {
            x: 0,
            opacity: 1,
          },
        }}
      >
        <Component {...pageProps} />
      </motion.div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export default MyApp;
